name: Lint and Format Code

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install linters and formatters
        run: |
          pip install flake8 black

      - name: Run flake8 (Linting)
        run: |
          flake8 src tests
        continue-on-error: true

      - name: Run black (Formatting check)
        run: |
          black --check src tests
        continue-on-error: true
