name: Security Check

on:
  pull_request:
    branches:
      - "**"

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit (Static Analysis)
        run: |
          bandit -r src
