name: Run pytest in 3.10

on:
  workflow_run:
    workflows: ["Pytest 3.9"]
    branches: [main]
    types:
        - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install pytest pytest-cov

      - name: Run tests
        id: test
        run: pytest

      - name: Update Badge
        run: |
          if [[ "${{ steps.test.outcome }}" == "success" ]]; then
            echo "Generating PASS badge for Python 3.10"
            curl "https://img.shields.io/badge/Python%203.10-Pass-brightgreen.svg" -o "docs/badges/python_310_pass.svg"
            sed -i 's|!\[Python 3.10.*|![Python 3.10](./python_310_pass.svg)|g' README.md
          else
            echo "Generating FAIL badge for Python 3.10"
            curl "https://img.shields.io/badge/Python%203.10-Fail-red.svg" -o "docs/badges/python_310_fail.svg"
            sed -i 's|!\[Python 3.10.*|![Python 3.10](./python_310_fail.svg)|g' README.md
          fi
        id: save-result

      - name: Commit and Push Badge Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md ./docs/badges/*.svg
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update badges for all Python versions"
            git push
          fi