name: Test and Update Badges

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pyenv dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
          libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
          liblzma-dev python-openssl git

      - name: Install pyenv
        run: curl https://pyenv.run | bash
        shell: bash

      - name: Configure pyenv
        run: |
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init --path)"' >> $GITHUB_ENV
          echo 'eval "$(pyenv init -)"' >> $GITHUB_ENV
          echo 'eval "$(pyenv virtualenv-init -)"' >> $GITHUB_ENV
          source $GITHUB_ENV
        shell: bash

      - name: Install Python with pyenv and create venv
        run: |
          pyenv install $(cat .python-version)
          pyenv exec python -m venv .venv

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry env use $(pyenv which python)
          poetry install --no-root

      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml --cov-report=term

      - name: Generate Coverage Badge
        run: |
          poetry run coverage-badge -o coverage.svg -f

      - name: Update README.md with coverage badge
        run: |
          sed -i 's|\[!\[coverage\](.*)|\[!\[coverage\](./coverage.svg)|g' README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add coverage.svg README.md
          git commit -m "Update coverage badge"
          git push
