name: Version Bump

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  version-bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: pip install bump2version

      - name: Determine version bump type
        id: bump_type
        run: |
          # Default to patch if no specific label is found
          bump="patch"

          # Loop through PR labels to check for major/minor/patch
          for label in "${{ github.event.pull_request.labels.*.name }}"; do
            if [[ "$label" == "major" ]]; then
              bump="major"
            elif [[ "$label" == "minor" ]]; then
              bump="minor"
            fi
          done

          echo "Version bump level: $bump"
          echo "::set-output name=version_bump::$bump"

      - name: Bump version
        run: |
          bump2version ${{ steps.bump_type.outputs.version_bump }}